# Install script for directory: /home/svilsen/seqan/seqan-src/tests

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Debug")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/consensus_v2/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/alignment_free/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/simple_intervals_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/multiple_translation_units/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/index/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/random/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/bed_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/reduced_aminoacid/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/align_extend/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/bam_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/translation/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/modifier/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/gff_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/modifier_cyclic_shape/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/align/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/graph_types/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/sequence/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/store/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/graph_msa/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/sequence_journaled/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/score/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/roi_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/cuda/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/misc/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/realign/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/arg_parse/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/align_split/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/basic/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/stream/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/journaled_set/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/seq_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/swift_local/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/statistics/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/graph_algorithms/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/find/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/vcf_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/align_profile/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/map/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/consensus/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/pipe/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/graph_align/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/ucsc_io/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/parallel/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/parse_lm/cmake_install.cmake")
  INCLUDE("/home/svilsen/seqan/seqan-build/debug/tests/seeds/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

