# CMake generated Testfile for 
# Source directory: /home/svilsen/seqan/seqan-src/tests
# Build directory: /home/svilsen/seqan/seqan-build/debug/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(consensus_v2)
SUBDIRS(alignment_free)
SUBDIRS(simple_intervals_io)
SUBDIRS(multiple_translation_units)
SUBDIRS(index)
SUBDIRS(random)
SUBDIRS(bed_io)
SUBDIRS(reduced_aminoacid)
SUBDIRS(align_extend)
SUBDIRS(bam_io)
SUBDIRS(translation)
SUBDIRS(modifier)
SUBDIRS(gff_io)
SUBDIRS(modifier_cyclic_shape)
SUBDIRS(align)
SUBDIRS(graph_types)
SUBDIRS(sequence)
SUBDIRS(store)
SUBDIRS(graph_msa)
SUBDIRS(sequence_journaled)
SUBDIRS(score)
SUBDIRS(roi_io)
SUBDIRS(cuda)
SUBDIRS(misc)
SUBDIRS(realign)
SUBDIRS(arg_parse)
SUBDIRS(align_split)
SUBDIRS(basic)
SUBDIRS(stream)
SUBDIRS(journaled_set)
SUBDIRS(seq_io)
SUBDIRS(swift_local)
SUBDIRS(statistics)
SUBDIRS(graph_algorithms)
SUBDIRS(find)
SUBDIRS(vcf_io)
SUBDIRS(align_profile)
SUBDIRS(map)
SUBDIRS(consensus)
SUBDIRS(pipe)
SUBDIRS(graph_align)
SUBDIRS(ucsc_io)
SUBDIRS(parallel)
SUBDIRS(parse_lm)
SUBDIRS(seeds)
