// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vmatchMultiPatternSeqAn
Rcpp::List vmatchMultiPatternSeqAn(SEXP pattern, SEXP subject, int max_mismatch);
RcppExport SEXP STRMPS_vmatchMultiPatternSeqAn(SEXP patternSEXP, SEXP subjectSEXP, SEXP max_mismatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< int >::type max_mismatch(max_mismatchSEXP);
    rcpp_result_gen = Rcpp::wrap(vmatchMultiPatternSeqAn(pattern, subject, max_mismatch));
    return rcpp_result_gen;
END_RCPP
}
