// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// vmatchMultiPatternSeqAn
Eigen::MatrixXd vmatchMultiPatternSeqAn(SEXP forwardPattern, SEXP reversePattern, SEXP subject, SEXP idVector, int max_mismatch, int indels);
RcppExport SEXP _STRMPS_vmatchMultiPatternSeqAn(SEXP forwardPatternSEXP, SEXP reversePatternSEXP, SEXP subjectSEXP, SEXP idVectorSEXP, SEXP max_mismatchSEXP, SEXP indelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type forwardPattern(forwardPatternSEXP);
    Rcpp::traits::input_parameter< SEXP >::type reversePattern(reversePatternSEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type idVector(idVectorSEXP);
    Rcpp::traits::input_parameter< int >::type max_mismatch(max_mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type indels(indelsSEXP);
    rcpp_result_gen = Rcpp::wrap(vmatchMultiPatternSeqAn(forwardPattern, reversePattern, subject, idVector, max_mismatch, indels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STRMPS_vmatchMultiPatternSeqAn", (DL_FUNC) &_STRMPS_vmatchMultiPatternSeqAn, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_STRMPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
