# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' vmatchMultiPatternSeqAn
#' @description
#' Function achieving the same as the wrapper functions for \code{XStringSet_vmatch_pattern} allowing for multiple patterns.
#' This alternate method is based on the external SeqAn C++ library.
#'
#' @param forwardPattern a vector of strings.
#' @param reversePattern a vector of strings.
#' @param subject a vector of strings.
#' @param idVector a vector of numbers used for sequences identification.
#' @param max_mismatch the maximum allowed number of mismatching bases between the pattern and the subject.
#'
#' @details
#' \code{vmatchMultiPatternSeqAn}.
vmatchMultiPatternSeqAn <- function(forwardPattern, reversePattern, subject, idVector, max_mismatch, indels = 0L) {
    .Call('_STRMPS_vmatchMultiPatternSeqAn', PACKAGE = 'STRMPS', forwardPattern, reversePattern, subject, idVector, max_mismatch, indels)
}

