# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' vmatchMultiPatternSeqAn
#' @description
#' Function achieving the same as the wrapper functions for \code{XStringSet_vmatch_pattern} allowing for multiple patterns.
#' This alternate method is based on the external SeqAn C++ library.
#'
#' @param pattern a vector of strings.
#'
#' @param subject a vector of strings.
#'
#' @param max_mismatch the maximum allowed number of mismatching bases between the pattern and the subject.
#'
#'
#' @details
#' \code{vmatchMultiPatternSeqAn}.
#'
#' @export
vmatchMultiPatternSeqAn <- function(pattern, subject, max_mismatch) {
    .Call('STRMPS_vmatchMultiPatternSeqAn', PACKAGE = 'STRMPS', pattern, subject, max_mismatch)
}

