# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' getAlignmentNeighbourScore
#'
#' @description
#' Gets the alignment score of specified neighbours.
#'
#' @param parent the parent string with which the neighbours are matched.
#'
#' @param neighbours potential variations of the parent string.
#'
#' @param gapOpening the penalty for opening a new gap (positive value).
#'
#' @param gapExtension the penalty for extenting a gap (positive value).
#'
#' @export
getAlignmentNeighbourScore <- function(parent, neighbours, mismatch, gapOpening, gapExtension) {
    .Call('STRMPS_getAlignmentNeighbourScore', PACKAGE = 'STRMPS', parent, neighbours, mismatch, gapOpening, gapExtension)
}

#' @title
#' vmatchMultiPattern
#' @description
#' Wrapper function for \code{XStringSet_vmatch_pattern} allowing for multiple patterns.
#' Alternate version of vmatchMultiPattern.
#'
#' @param pattern an XStringSet-object.
#'
#' @param subject an XStringSet-object.
#'
#' @param max_mismatch the maximum allowed number of mismatching bases between the pattern and the subject.
#'
#' @param min_mismatch the minimum allowed number of mismatching bases between the pattern and the subject.
#'
#' @details
#' \code{vmatchMultiPattern}...
#'
#' @export
vmatchMultiPattern <- function(pattern, subject, max_mismatch, min_mismatch, with_indels, fixed, algorithm, matches_as, envir) {
    .Call('STRMPS_vmatchMultiPattern', PACKAGE = 'STRMPS', pattern, subject, max_mismatch, min_mismatch, with_indels, fixed, algorithm, matches_as, envir)
}

#' @title
#' vmatchMultiPatternAlternate
#' @description
#' Wrapper function for \code{XStringSet_vmatch_pattern} allowing for multiple patterns.
#'
#' @param pattern an XStringSet-object.
#'
#' @param subject an XStringSet-object.
#'
#' @param max_mismatch the maximum allowed number of mismatching bases between the pattern and the subject.
#'
#' @param min_mismatch the minimum allowed number of mismatching bases between the pattern and the subject.
#'
#' @details
#' \code{vmatchMultiPatternAlternate}...
#'
#' @export
vmatchMultiPatternAlternate <- function(pattern, subject, max_mismatch, min_mismatch, with_indels, fixed, algorithm, matches_as, envir) {
    .Call('STRMPS_vmatchMultiPatternAlternate', PACKAGE = 'STRMPS', pattern, subject, max_mismatch, min_mismatch, with_indels, fixed, algorithm, matches_as, envir)
}

#' @title
#' vmatchMultiPatternSeqAn
#' @description
#' Function achieving the same as the wrapper functions for \code{XStringSet_vmatch_pattern} allowing for multiple patterns.
#' This alternate method is based on the external SeqAn C++ library.
#'
#' @param pattern a vector of strings.
#'
#' @param subject a vector of strings.
#'
#' @param max_mismatch the maximum allowed number of mismatching bases between the pattern and the subject.
#'
#'
#' @details
#' \code{vmatchMultiPatternSeqAn}.
#'
#' @export
vmatchMultiPatternSeqAn <- function(pattern, subject, max_mismatch) {
    .Call('STRMPS_vmatchMultiPatternSeqAn', PACKAGE = 'STRMPS', pattern, subject, max_mismatch)
}

